name: Publish Binary Cache
on:
  push:
    branches: [main]
    tags: ["v*"]
    paths-ignore: ["docs/**", "*.md"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: pplanel/nixcache/.github/workflows/publish-cache.yml@main
    secrets: inherit
